const PRESIDENTS: [&str; 45] = [
    "George_Washington",
    "John_Adams",
    "Thomas_Jefferson",
    "James_Madison",
    "James_Monroe",
    "John_Quincy_Adams",
    "Andrew_Jackson",
    "Martin_Van_Buren",
    "William_Henry_Harrison",
    "John_Tyler",
    "James_K._Polk",
    "Zachary_Taylor",
    "Millard_Fillmore",
    "Franklin_Pierce",
    "James_Buchanan",
    "Abraham_Lincoln",
    "Andrew_Johnson",
    "Ulysses_S._Grant",
    "Rutherford_B._Hayes",
    "James_A._Garfield",
    "Chester_A._Arthur",
    "Grover_Cleveland",
    "Benjamin_Harrison",
    "William_McKinley",
    "Theodore_Roosevelt",
    "William_Howard_Taft",
    "Woodrow_Wilson",
    "Warren_G._Harding",
    "Calvin_Coolidge",
    "Herbert_Hoover",
    "Franklin_D._Roosevelt",
    "Harry_S._Truman",
    "Dwight_D._Eisenhower",
    "John_F._Kennedy",
    "Lyndon_B._Johnson",
    "Richard_Nixon",
    "Gerald_Ford",
    "Jimmy_Carter",
    "Ronald_Reagan",
    "George_H._W._Bush",
    "Bill_Clinton",
    "George_W._Bush",
    "Barack_Obama",
    "Donald_Trump",
    "Joe_Biden",
];

// List of European countries with space converted to underscore
const EUROPEAN_COUNTRIES: [&str; 49] = [
    "Albania",
    "Andorra",
    "Armenia",
    "Austria",
    "Azerbaijan",
    "Belarus",
    "Belgium",
    "Bosnia_and_Herzegovina",
    "Bulgaria",
    "Croatia",
    "Cyprus",
    "Czech_Republic",
    "Denmark",
    "Estonia",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Greece",
    "Hungary",
    "Iceland",
    "Ireland",
    "Italy",
    "Kazakhstan",
    "Kosovo",
    "Latvia",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Malta",
    "Moldova",
    "Monaco",
    "Montenegro",
    "Netherlands",
    "North_Macedonia",
    "Norway",
    "Poland",
    "Portugal",
    "Romania",
    "Russia",
    "San_Marino",
    "Serbia",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Ukraine",
    "Vatican_City",
];

// List of US states with space converted to underscore
const US_STATES: [&str; 50] = [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New_Hampshire",
    "New_Jersey",
    "New_Mexico",
    "New_York",
    "North_Carolina",
    "North_Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode_Island",
    "South_Carolina",
    "South_Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West_Virginia",
    "Wisconsin",
    "Wyoming",
];

// List of Asian countries with space converted to underscore
const ASIAN_COUNTRIES: [&str; 43] = [
    "Afghanistan",
    "Bahrain",
    "Bangladesh",
    "Bhutan",
    "Brunei",
    "Cambodia",
    "China",
    "East_Timor",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Japan",
    "Jordan",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Lebanon",
    "Malaysia",
    "Maldives",
    "Mongolia",
    "Myanmar",
    "Nepal",
    "North_Korea",
    "Oman",
    "Pakistan",
    "Palestine",
    "Philippines",
    "Qatar",
    "Saudi_Arabia",
    "Singapore",
    "South_Korea",
    "Sri_Lanka",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Thailand",
    "Turkey",
    "Turkmenistan",
    "United_Arab_Emirates",
    "Uzbekistan",
    "Vietnam",
    "Yemen",
];

// List of Latin American countries with space converted to underscore
const LATIN_AMERICAN_COUNTRIES: [&str; 20] = [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Costa_Rica",
    "Cuba",
    "Dominican_Republic",
    "Ecuador",
    "El_Salvador",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
];

// List of Philosopher with space converted to underscore
const PHILOSOPHERS: [&str; 38] = [
    "Aristotle",
    "Confucius",
    "Socrates",
    "Plato",
    "Immanuel_Kant",
    "Friedrich_Nietzsche",
    "David_Hume",
    "John_Locke",
    "Maximilien_Robespierre",
    "René_Descartes",
    "Georg_Wilhelm_Friedrich_Hegel",
    "Karl_Marx",
    "Ludwig_Wittgenstein",
    "Edmund_Husserl",
    "Martin_Heidegger",
    "Jean-Paul_Sartre",
    "Michel_Foucault",
    "Jacques_Derrida",
    "Gilles_Deleuze",
    "Jean_Baudrillard",
    "Richard_Rorty",
    "John_Rawls",
    "Jürgen_Habermas",
    "Jean-François_Lyotard",
    "Saul_Kripke",
    "Rudolf_Carnap",
    "Hilary_Putnam",
    "Betrand_Russell",
    "Karl_Popper",
    "Thomas_Kuhn",
    "Paul_Feyerabend",
    "Imre_Lakatos",
    "Pierre_Duhem",
    "Willard_Van_Orman_Quine",
    "Carl_Gustav_Hempel",
    "Christian_Heinrich_von_Nagel",
    "Nelson_Goodman",
    "Arthur_Schopenhauer",
];

// List of Mathematicians with space converted to underscore
const MATHEMATICIANS: [&str; 39] = [
    "Euclid",
    "Pythagoras",
    "Archimedes",
    "Isaac_Newton",
    "Carl_Friedrich_Gauss",
    "Leonhard_Euler",
    "Pierre-Simon_Laplace",
    "Joseph_Fourier",
    "Bernhard_Riemann",
    "Henri_Poincaré",
    "David_Hilbert",
    "Georg_Cantor",
    "Felix_Klein",
    "Emmy_Noether",
    "Kurt_Gödel",
    "Alan_Turing",
    "John_von_Neumann",
    "Paul_Erdős",
    "Andrew_Wiles",
    "Grigori_Perelman",
    "Terence_Tao",
    "Maryam_Mirzakhani",
    "Srinivasa_Ramanujan",
    "Évariste_Galois",
    "Niels_Henrik_Abel",
    "Sophie_Germain",
    "Émilie_du_Châtelet",
    "Ada_Lovelace",
    "Sofia_Kovalevskaya",
    "Emmy_Noether",
    "Hypatia",
    "Maria_Gaetana_Agnesi",
    "Florence_Nightingale",
    "Grace_Hopper",
    "Dorothy_Vaughan",
    "Mary_Jackson",
    "Katherine_Johnson",
    "Margaret_Hamilton",
    "Ada_Lovelace",
];

// List of Physicists with space converted to underscore
const PHYSICISTS: [&str; 32] = [
    "Isaac_Newton",
    "Albert_Einstein",
    "Galileo_Galilei",
    "Nikola_Tesla",
    "James_Clerk_Maxwell",
    "Michael_Faraday",
    "Erwin_Schrödinger",
    "Werner_Heisenberg",
    "Max_Planck",
    "Niels_Bohr",
    "Richard_Feynman",
    "Enrico_Fermi",
    "Paul_Dirac",
    "Ernest_Rutherford",
    "Marie_Curie",
    "Pierre_Curie",
    "Lise_Meitner",
    "Emmy_Noether",
    "Jocelyn_Bell_Burnell",
    "Chien-Shiung_Wu",
    "Maria_Goeppert_Mayer",
    "Dorothy_Crowfoot_Hodgkin",
    "Gertrude_B._Elion",
    "Rita_Levi-Montalcini",
    "Ada_Yonath",
    "Françoise_Barré-Sinoussi",
    "Carol_W._Greider",
    "Elizabeth_Blackburn",
    "May-Britt_Moser",
    "Tu_Youyou",
    "Donna_Strickland",
    "Marie_Curie",
];

// List of economists with space converted to underscore
const ECONOMISTS: [&str; 40] = [
    "Adam_Smith",
    "David_Ricardo",
    "Thomas_Malthus",
    "John_Stuart_Mill",
    "Karl_Marx",
    "Alfred_Marshall",
    "Ludwig_von_Mises",
    "Friedrich_Hayek",
    "John_Maynard_Keynes",
    "Milton_Friedman",
    "Paul_Samuelson",
    "Amartya_Sen",
    "Joseph_Stiglitz",
    "Robert_Solow",
    "Gary_Becker",
    "George_Akerlof",
    "Robert_Shiller",
    "Elinor_Ostrom",
    "Esther_Duflo",
    "Abhijit_Banerjee",
    "Angus_Deaton",
    "Thomas_Piketty",
    "Richard_Thaler",
    "Daniel_Kahneman",
    "Vernon_Smith",
    "Elinor_Ostrom",
    "Oliver_Hart",
    "Bengt_Holmström",
    "Jean_Tirole",
    "William_Nordhaus",
    "Paul_Romer",
    "Robert_Lucas",
    "James_Buchanan",
    "Milton_Friedman",
    "George_Stigler",
    "Ronald_Coase",
    "Gary_Becker",
    "Douglass_North",
    "Robert_Fogel",
    "Amartya_Sen",
];

// List of political ideologies with space converted to underscore
const POLITICAL_IDEOLOGIES: [&str; 8] = [
    "Anarchism",
    "Communism",
    "Conservatism",
    "Fascism",
    "Liberalism",
    "Libertarianism",
    "Marxism",
    "Socialism",
];

const POLITICAL_IDEOLOGIES2: [&str; 80] = [
    "Anti-establishment",
    "Centrism",
    "Hardline",
    "Left-wing_politics",
    "Reactionary",
    "Revolutionary",
    "Right-wing_politics",
    "The_Establishment",
    "Accelerationism",
    "Agrarianism",
    "Anarchism",
    "Authoritarianism",
    "Capitalism",
    "Centrism",
    "Christian_democracy",
    "Collectivism",
    "Colonialism",
    "Communalism",
    "Communism",
    "Communitarianism",
    "Conservatism",
    "Constitutionalism",
    "Corporatism",
    "Democracy",
    "Distributism",
    "Environmentalism",
    "Extremism",
    "Familialism",
    "Fanaticism",
    "Nazism",
    "Federalism",
    "Feminism",
    "Fundamentalism",
    "Globalism",
    "Green",
    "Imperialism",
    "Individualism",
    "Industrialism",
    "Intellectualism",
    "Interculturalism",
    "Internationalism",
    "Islamism",
    "Leftism",
    "Legalism",
    "Liberalism",
    "Libertarianism",
    "Localism",
    "Marxism",
    "Masculism",
    "Militarism",
    "Monarchism",
    "Monoculturalism",
    "Multiculturalism",
    "Nationalism",
    "Nihilism",
    "Pacifism",
    "Pluralism",
    "Political_radicalism",
    "Populism",
    "Progressivism",
    "Reformism",
    "Regionalism",
    "Republicanism",
    "Modern",
    "Rightism",
    "Royalism",
    "Secularism",
    "Separatism",
    "Social_anarchism",
    "Social_credit",
    "Social_democracy",
    "Socialism",
    "Statism",
    "Syncretism",
    "Technocracy",
    "Third_Way",
    "Totalitarianism",
    "Utilitarianism",
    "White_supremacy",
    "Zionism",
];

// List of types of government with space converted to underscore
const TYPES_OF_GOVERNMENT: [&str; 17] = [
    "Anarchy",
    "Aristocracy",
    "Autocracy",
    "Bureaucracy",
    "Democracy",
    "Despotism",
    "Dictatorship",
    "Feudalism",
    "Kleptocracy",
    "Meritocracy",
    "Monarchy",
    "Oligarchy",
    "Plutocracy",
    "Republic",
    "Socialism",
    "Theocracy",
    "Totalitarianism",
];

const TYPES_OF_GOVERNMENT2: [&str; 32] = [
    "Anarchy",
    "Aristocracy",
    "Authoritarianism",
    "Bureaucracy",
    "Capitalism",
    "Confederation",
    "Colonialism",
    "Communism",
    "Corporatocracy",
    "Democracy",
    "Electocracy",
    "Ergatocracy",
    "Fascism",
    "Federalism",
    "Feudalism",
    "Geniocracy",
    "Imperialism",
    "Kakistocracy",
    "Kleptocracy",
    "Logocracy",
    "Meritocracy",
    "Military_dictatorship",
    "Monarchy",
    "Oligarchy",
    "Plutocracy",
    "Republicanism",
    "Socialism",
    "Statism",
    "Technocracy",
    "Theocracy",
    "Totalitarianism",
    "Tribalism",
];

const TYPES_OF_GOVERNMENT3: [&str; 22] = [
    "Agrarianism",
    "Anarchism",
    "Authoritarianism",
    "Centrism",
    "Christian_democracy",
    "Collectivism",
    "Communalism",
    "Communitarianism",
    "Conservatism",
    "Constitutionalism",
    "Corporatism",
    "Distributism",
    "Egalitarianism",
    "Environmentalism",
    "Extremism",
    "Familialism",
    "Fanaticism",
    "Fascism",
    "Feminism",
    "Fundamentalism",
    "Liberalism",
    "Progressivism",
];

const SOCIAL_SERVICE: [&str; 7] = [
    "Socialism",
    "Social_democracy",
    "Social_anarchism",
    "Social_credit",
    "Social_liberalism",
    "Social_market_economy",
    "Socialism_with_Chinese_characteristics",
];

const SOCIAL_SERVICE2: [&str; 15] = [
    "Social_insurance",
    "Law_enforcement",
    "Unemployment_benefits",
    "National_healthcare",
    "Public_education",
    "Military",
    "Espionage",
    "Regulation",
    "Environmental_regulation",
    "Banking_regulation",
    "Food_inspection",
    "Municipal",
    "Traffic_lights",
    "Sanitation",
    "Street_cleaning",
];

// List of high profile communists
const COMMUNISTS: [&str; 32] = [
    "Karl_Marx",
    "Vladimir_Lenin",
    "Joseph_Stalin",
    "Mao_Zedong",
    "Fidel_Castro",
    "Che_Guevara",
    "Nikita_Khrushchev",
    "Leon_Trotsky",
    "Ho_Chi_Minh",
    "Kim_Il-sung",
    "Kim_Jong-il",
    "Kim_Jong-un",
    "Pol_Pot",
    "Josip_Broz_Tito",
    "Enver_Hoxha",
    "Nikolai_Bukharin",
    "Leonid_Brezhnev",
    "Mikhail_Gorbachev",
    "Klement_Gottwald",
    "Walter_Ulbricht",
    "Erich_Honecker",
    "Erich_Mielke",
    "Willy_Brandt",
    "Egon_Krenz",
    "Angela_Davis",
    "Rosa_Luxemburg",
    "Clara_Zetkin",
    "Emma_Goldman",
    "Louise_Michel",
    "Lucy_Parsons",
    "Marianne_Weber",
    "Marie_Sophie_Schwartz",
];

// List of Critical Theorists
const CRITICAL_THEORISTS: [&str; 23] = [
    "Max_Horkheimer",
    "Theodor_Adorno",
    "Herbert_Marcuse",
    "Walter_Benjamin",
    "Erich_Fromm",
    "Friedrich_Pollock",
    "Leo_Löwenthal",
    "Jürgen_Habermas",
    "Alfred_Schütz",
    "Karl_Mannheim",
    "Otto_Kirchheimer",
    "Franz_Neumann",
    "Hannah_Arendt",
    "Paul_Lazarsfeld",
    "Siegfried_Kracauer",
    "Karl_Polanyi",
    "Richard_Sorge",
    "Wilhelm_Reich",
    "Erich_Mielke",
    "Erich_Honecker",
    "Willy_Brandt",
    "Egon_Krenz",
    "Karl_Korsch",
];

// List of woke terms
const WOKE_TERMS: [&str; 23] = [
    "Woke",
    "Cancel_culture",
    "Critical_race_theory",
    "Intersectionality",
    "White_privilege",
    "Systemic_racism",
    "Microaggression",
    "Cultural_appropriation",
    "Safe_space",
    "Trigger_warning",
    "Social_justice",
    "Political_correctness",
    "Identity_politics",
    "Cultural_marxism",
    "White_fragility",
    "Allyship",
    "Gaslighting",
    "Mansplaining",
    "Manspreading",
    "Toxic_masculinity",
    "Patriarchy",
    "Misogyny",
    "Misandry",
];

// List of fascist leaders with space converted to underscore
const FASCISTS: [&str; 16] = [
    "Benito_Mussolini",
    "Adolf_Hitler",
    "Francisco_Franco",
    "Ante_Pavelić",
    "Ion_Antonescu",
    "Corneliu_Zelea_Codreanu",
    "Dimitrije_Ljotić",
    "Vidkun_Quisling",
    "Pierre_Laval",
    "Philippe_Pétain",
    "Emilio_Mola",
    "José_María_Gil-Robles",
    "Carlos_Arias_Navarro",
    "Luis_Carrero_Blanco",
    "Rodrigo_Rato",
    "Oswald_Mosley",
];

// List of list of page titles
/*
    PRESIDENTS,
    EUROPEAN_COUNTRIES,
    US_STATES,
    ASIAN_COUNTRIES,
    PHILOSOPHERS,
    LATIN_AMERICAN_COUNTRIES,
    POLITICAL_IDEOLOGIES,
    POLITICAL_IDEOLOGIES2,
    TYPES_OF_GOVERNMENT,
    TYPES_OF_GOVERNMENT2,
    TYPES_OF_GOVERNMENT3,
    SOCIAL_SERVICE,
    SOCIAL_SERVICE2,
    COMMUNISTS,
    CRITICAL_THEORISTS,
    WOKE_TERMS,
    FASCISTS,
];
*/

// Count of all page titles
pub const fn count_page_titles() -> usize {
    PRESIDENTS.len()
        + EUROPEAN_COUNTRIES.len()
        + US_STATES.len()
        + ASIAN_COUNTRIES.len()
        + PHILOSOPHERS.len()
        + MATHEMATICIANS.len()
        + PHYSICISTS.len()
        + ECONOMISTS.len()
        + POLITICAL_IDEOLOGIES.len()
        + POLITICAL_IDEOLOGIES2.len()
        + TYPES_OF_GOVERNMENT.len()
        + TYPES_OF_GOVERNMENT2.len()
        + TYPES_OF_GOVERNMENT3.len()
        + SOCIAL_SERVICE.len()
        + SOCIAL_SERVICE2.len()
        + COMMUNISTS.len()
        + CRITICAL_THEORISTS.len()
        + WOKE_TERMS.len()
        + FASCISTS.len()
}

// Build a list of page titles
// Use a set to avoid duplicates
use std::collections::HashSet;

pub fn build_page_titles() -> Vec<&'static str> {
    let mut titles = HashSet::new();
    titles.extend(PRESIDENTS);
    titles.extend(EUROPEAN_COUNTRIES);
    titles.extend(US_STATES);
    titles.extend(ASIAN_COUNTRIES);
    titles.extend(PHILOSOPHERS);
    titles.extend(MATHEMATICIANS);
    titles.extend(PHYSICISTS);
    titles.extend(ECONOMISTS);
    titles.extend(POLITICAL_IDEOLOGIES);
    titles.extend(POLITICAL_IDEOLOGIES2);
    titles.extend(TYPES_OF_GOVERNMENT);
    titles.extend(TYPES_OF_GOVERNMENT2);
    titles.extend(TYPES_OF_GOVERNMENT3);
    titles.extend(SOCIAL_SERVICE);
    titles.extend(SOCIAL_SERVICE2);
    titles.extend(COMMUNISTS);
    titles.extend(CRITICAL_THEORISTS);
    titles.extend(WOKE_TERMS);
    titles.extend(FASCISTS);

    let titles_vec: Vec<&'static str> = titles.into_iter().collect();
    titles_vec
}
